# Generated by Django 5.2.7 on 2025-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_addregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='addregistration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courseimage'),
        ),
    ]
