# Generated by Django 5.2.7 on 2025-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_addregistration_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addregistration',
            old_name='name',
            new_name='coursedescription',
        ),
        migrations.RenameField(
            model_name='addregistration',
            old_name='image',
            new_name='courseimage',
        ),
        migrations.RemoveField(
            model_name='addregistration',
            name='price',
        ),
        migrations.AddField(
            model_name='addregistration',
            name='coursefee',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addregistration',
            name='coursename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addregistration',
            name='mentorname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
