# Generated by Django 5.2.7 on 2025-10-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_rename_name_addregistration_coursedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addregistration',
            name='coursetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
