# Generated by Django 5.2.7 on 2026-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_addregistration_coursetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addregistration',
            name='coursedescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='addregistration',
            name='coursename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addregistration',
            name='courserating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addregistration',
            name='mentorname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
