# Generated by Django 5.2.7 on 2026-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_alter_addregistration_coursedescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addregistration',
            name='coursefee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
